server:
  port: 9012
spring:
  application:
    name: DSA-PRACTICE
  profiles:
    active: log4j

  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    url: 'jdbc:h2:mem:devdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: "Rahul"
      password: "12345"
input:
  type: array
  items:
    type: int
    values: 5,8,3,2,9,7,10,29,51,15,56,25,71,17,18,72,19
      



    

