server:
  port: 9012
spring:
  application:
    name: DSA-PRACTICE
  profiles:
    active: log4j,input

  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    url: 'jdbc:h2:mem:devdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: "Rahul"
      password: "12345"
      



    

